/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SessionService } from "../session.service";
import { SessionCreateInput } from "./SessionCreateInput";
import { Session } from "./Session";
import { SessionFindManyArgs } from "./SessionFindManyArgs";
import { SessionWhereUniqueInput } from "./SessionWhereUniqueInput";
import { SessionUpdateInput } from "./SessionUpdateInput";
import { NetworkActivityFindManyArgs } from "../../networkActivity/base/NetworkActivityFindManyArgs";
import { NetworkActivity } from "../../networkActivity/base/NetworkActivity";
import { NetworkActivityWhereUniqueInput } from "../../networkActivity/base/NetworkActivityWhereUniqueInput";
import { RecordingFindManyArgs } from "../../recording/base/RecordingFindManyArgs";
import { Recording } from "../../recording/base/Recording";
import { RecordingWhereUniqueInput } from "../../recording/base/RecordingWhereUniqueInput";

export class SessionControllerBase {
  constructor(protected readonly service: SessionService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Session })
  async createSession(
    @common.Body() data: SessionCreateInput
  ): Promise<Session> {
    return await this.service.createSession({
      data: data,
      select: {
        createdAt: true,
        endTime: true,
        id: true,
        sessionId: true,
        startTime: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Session] })
  @ApiNestedQuery(SessionFindManyArgs)
  async sessions(@common.Req() request: Request): Promise<Session[]> {
    const args = plainToClass(SessionFindManyArgs, request.query);
    return this.service.sessions({
      ...args,
      select: {
        createdAt: true,
        endTime: true,
        id: true,
        sessionId: true,
        startTime: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Session })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async session(
    @common.Param() params: SessionWhereUniqueInput
  ): Promise<Session | null> {
    const result = await this.service.session({
      where: params,
      select: {
        createdAt: true,
        endTime: true,
        id: true,
        sessionId: true,
        startTime: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Session })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSession(
    @common.Param() params: SessionWhereUniqueInput,
    @common.Body() data: SessionUpdateInput
  ): Promise<Session | null> {
    try {
      return await this.service.updateSession({
        where: params,
        data: data,
        select: {
          createdAt: true,
          endTime: true,
          id: true,
          sessionId: true,
          startTime: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Session })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSession(
    @common.Param() params: SessionWhereUniqueInput
  ): Promise<Session | null> {
    try {
      return await this.service.deleteSession({
        where: params,
        select: {
          createdAt: true,
          endTime: true,
          id: true,
          sessionId: true,
          startTime: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/networkActivities")
  @ApiNestedQuery(NetworkActivityFindManyArgs)
  async findNetworkActivities(
    @common.Req() request: Request,
    @common.Param() params: SessionWhereUniqueInput
  ): Promise<NetworkActivity[]> {
    const query = plainToClass(NetworkActivityFindManyArgs, request.query);
    const results = await this.service.findNetworkActivities(params.id, {
      ...query,
      select: {
        activityData: true,
        activityId: true,
        createdAt: true,
        id: true,

        session: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/networkActivities")
  async connectNetworkActivities(
    @common.Param() params: SessionWhereUniqueInput,
    @common.Body() body: NetworkActivityWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      networkActivities: {
        connect: body,
      },
    };
    await this.service.updateSession({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/networkActivities")
  async updateNetworkActivities(
    @common.Param() params: SessionWhereUniqueInput,
    @common.Body() body: NetworkActivityWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      networkActivities: {
        set: body,
      },
    };
    await this.service.updateSession({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/networkActivities")
  async disconnectNetworkActivities(
    @common.Param() params: SessionWhereUniqueInput,
    @common.Body() body: NetworkActivityWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      networkActivities: {
        disconnect: body,
      },
    };
    await this.service.updateSession({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/recordings")
  @ApiNestedQuery(RecordingFindManyArgs)
  async findRecordings(
    @common.Req() request: Request,
    @common.Param() params: SessionWhereUniqueInput
  ): Promise<Recording[]> {
    const query = plainToClass(RecordingFindManyArgs, request.query);
    const results = await this.service.findRecordings(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        maskedFields: true,
        recordingId: true,

        session: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/recordings")
  async connectRecordings(
    @common.Param() params: SessionWhereUniqueInput,
    @common.Body() body: RecordingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      recordings: {
        connect: body,
      },
    };
    await this.service.updateSession({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/recordings")
  async updateRecordings(
    @common.Param() params: SessionWhereUniqueInput,
    @common.Body() body: RecordingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      recordings: {
        set: body,
      },
    };
    await this.service.updateSession({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/recordings")
  async disconnectRecordings(
    @common.Param() params: SessionWhereUniqueInput,
    @common.Body() body: RecordingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      recordings: {
        disconnect: body,
      },
    };
    await this.service.updateSession({
      where: params,
      data,
      select: { id: true },
    });
  }
}
